pipeline {
    // These are pre-build sections S 
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        COURSE = "jenkins"
    }
    options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    // parameters {
    //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    //     text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
    //     booleanParam(name: 'DEPLOY', defaultValue: false, description: 'Toggle this value')
    //     choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
    //     password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    // }
    // this is build section 
    stages {
        stage('Init') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 10-sg
                            terraform init
                        """
                    }
                    
                }
            }
        }
        stage('Plan') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                             cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('Deploy') {
            // input {
            //     message "Should we continue?"
            //     ok "Yes, we should."
            //     submitter "alice,bob"
            //     parameters {
            //         string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
            //     }
            // }
            // when {
            //     expression { "$params.DEPLOY" == "true" }
            // }
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Parallel Trigger'){
            parallel {
                stage('Bastion'){
                    steps {
                        script{
                            build job: '20-bastion',
                                wait: false, // wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('SG Rules'){
                    steps{
                        script{
                            build job: '30-sg-rules',
                                wait: false, // wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('ECR'){
                    steps{
                        script{
                            build job: '40-ecr',
                                wait: false, // wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('ACM'){
                    steps{
                        script{
                            build job: '70-acm',
                                wait: true, // wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('EKS'){
                    steps{
                        script{
                            build job: '90-eks',
                                wait: false, // wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
            }
        }
        stage('ALB'){
            steps{
                script{
                    build job: '80-frontend-alb',
                        wait: false, // wait for completion
                        propagate: false // Propagate status
                }
            }
        }
        
    }
    post {
        always {
            echo 'I will always say Hello again!' 
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo 'I will run if failure'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}